package com.simplepastapp.object;

import java.util.ArrayList;
import java.util.List;

public class SimplesPastFactory {

    public static final List<SimplePast> list = new ArrayList<>();

    public SimplesPastFactory() {
        list.add(new SimplePast(1, "say", "said", "saidid"));
        list.add(new SimplePast(2, "make", "made", "madeid"));
        list.add(new SimplePast(3, "go", "went", "goneid"));
        list.add(new SimplePast(4, "take", "took", "takenid"));
        list.add(new SimplePast(5, "come", "came", "comeid"));
        list.add(new SimplePast(6, "see", "saw", "seenid"));
        list.add(new SimplePast(7, "know", "knew", "knownid"));
        list.add(new SimplePast(8, "get", "got", "gotid"));
        list.add(new SimplePast(9, "give", "gave", "given"));
        list.add(new SimplePast(10, "find", "found", "found"));
        list.add(new SimplePast(11, "think", "thought", "thought"));
        list.add(new SimplePast(12, "tell", "told", "told"));
        list.add(new SimplePast(13, "become", "became", "become"));
        list.add(new SimplePast(14, "show", "showed", "shown"));
        list.add(new SimplePast(15, "leave", "left", "left"));
        list.add(new SimplePast(16, "feel", "felt", "felt"));
        list.add(new SimplePast(17, "put", "put", "put"));
        list.add(new SimplePast(18, "bring", "brought", "brought"));
        list.add(new SimplePast(19, "begin", "began", "begun"));
        list.add(new SimplePast(20, "keep", "kept", "kept"));
        list.add(new SimplePast(21, "hold", "held", "held"));
        list.add(new SimplePast(22, "write", "wrote", "written"));
        list.add(new SimplePast(23, "stand", "stood", "stood"));
        list.add(new SimplePast(24, "hear", "heard", "heard"));
        list.add(new SimplePast(25, "let", "let", "let"));
        list.add(new SimplePast(26, "mean", "meant", "meant"));
        list.add(new SimplePast(27, "set", "set", "set"));
        list.add(new SimplePast(28, "meet", "met", "met"));
        list.add(new SimplePast(29, "run", "ran", "run"));
        list.add(new SimplePast(30, "pay", "paid", "paid"));
        list.add(new SimplePast(31, "sit", "sat", "sat"));
        list.add(new SimplePast(32, "speak", "spoke", "spoken"));
        list.add(new SimplePast(33, "lie", "lay", "lain"));
        list.add(new SimplePast(34, "lead", "led", "led"));
        list.add(new SimplePast(35, "read", "read", "read"));
        list.add(new SimplePast(36, "grow", "grew", "grown"));
        list.add(new SimplePast(37, "lose", "lost", "lost"));
        list.add(new SimplePast(38, "fall", "fell", "fallen"));
        list.add(new SimplePast(39, "send", "sent", "sent"));
        list.add(new SimplePast(40, "build", "built", "built"));
        list.add(new SimplePast(41, "understand", "understood", "understood"));
        list.add(new SimplePast(42, "draw", "drew", "drawn"));
        list.add(new SimplePast(43, "break", "broke", "broken"));
        list.add(new SimplePast(44, "spend", "spent", "spent"));
        list.add(new SimplePast(45, "cut", "cut", "cut"));
        list.add(new SimplePast(46, "rise", "rose", "risen"));
        list.add(new SimplePast(47, "drive", "drove", "driven"));
        list.add(new SimplePast(48, "buy", "bought", "bought"));
        list.add(new SimplePast(49, "wear", "wore", "worn"));
        list.add(new SimplePast(50, "choose", "chose", "chosen"));
        list.add(new SimplePast(51, "seek", "sought", "sought"));
        list.add(new SimplePast(52, "throw", "threw", "thrown"));
        list.add(new SimplePast(53, "catch", "caught", "caught"));
        list.add(new SimplePast(54, "deal", "dealt", "dealt"));
        list.add(new SimplePast(55, "win", "won", "won"));
        list.add(new SimplePast(56, "forget", "forgot", "forgotten"));
        list.add(new SimplePast(57, "lay", "laid", "laid"));
        list.add(new SimplePast(58, "sell", "sold", "sold"));
        list.add(new SimplePast(59, "fight", "fought", "fought"));
        list.add(new SimplePast(60, "bear", "bore", "borne"));
        list.add(new SimplePast(61, "teach", "taught", "taught"));
        list.add(new SimplePast(62, "eat", "ate", "eaten"));
        list.add(new SimplePast(63, "sing", "sang", "sung"));
        list.add(new SimplePast(64, "strike", "struck", "struck"));
        list.add(new SimplePast(65, "hang", "hung", "hung"));
        list.add(new SimplePast(66, "shake", "shook", "shaken"));
        list.add(new SimplePast(67, "ride", "rode", "ridden"));
        list.add(new SimplePast(68, "feed", "fed", "fed"));
        list.add(new SimplePast(69, "shoot", "shot", "shot"));
        list.add(new SimplePast(70, "drink", "drank", "drunk"));
        list.add(new SimplePast(71, "hit", "hit", "hit"));
        list.add(new SimplePast(72, "arise", "arose", "arisen"));
        list.add(new SimplePast(73, "fly", "flew", "flown"));
        list.add(new SimplePast(74, "spread", "spread", "spread"));
        list.add(new SimplePast(75, "sleep", "slept", "slept"));
        list.add(new SimplePast(76, "cost", "cost", "cost"));
        list.add(new SimplePast(77, "beat", "beat", "beaten"));
        list.add(new SimplePast(78, "light", "lit", "lit"));
        list.add(new SimplePast(79, "bind", "bound", "bound"));
        list.add(new SimplePast(80, "cast", "cast", "cast"));
        list.add(new SimplePast(81, "hide", "hid", "hidden"));
        list.add(new SimplePast(82, "swing", "swung", "swung"));
        list.add(new SimplePast(83, "blow", "blew", "blown"));
        list.add(new SimplePast(84, "swim", "swam", "swum"));
        list.add(new SimplePast(85, "bend", "bent", "bent"));
        list.add(new SimplePast(86, "wake", "woke", "woken"));
        list.add(new SimplePast(87, "stick", "stuck", "stuck"));
        list.add(new SimplePast(88, "sweep", "swept", "swept"));
        list.add(new SimplePast(89, "undertake", "undertook", "undertaken"));
        list.add(new SimplePast(90, "shut", "shut", "shut"));
        list.add(new SimplePast(91, "steal", "stole", "stolen"));
        list.add(new SimplePast(92, "tear", "tore", "torn"));
        list.add(new SimplePast(93, "hurt", "hurt", "hurt"));
        list.add(new SimplePast(94, "ring", "rang", "rung"));
        list.add(new SimplePast(95, "lend", "lent", "lent"));
        list.add(new SimplePast(96, "sink", "sank", "sunk"));
        list.add(new SimplePast(97, "overcome", "overcame", "overcome"));
        list.add(new SimplePast(98, "freeze", "froze", "frozen"));
        list.add(new SimplePast(99, "shine", "shone", "shone"));
        list.add(new SimplePast(100, "withdraw", "withdrew", "withdrawn"));
    }
}
