package com.simplepastapp.datadriven;

import java.util.ArrayList;
import java.util.List;

public class SimplesPastFactory {

    public static final List<SimplePast> list = new ArrayList<>();

    SimplePast simplePast1 = new SimplePast(1, "say", "said", "saidid");
    SimplePast simplePast2 = new SimplePast(2, "make", "made", "madeid");
    SimplePast simplePast3 = new SimplePast(3, "go", "went", "goneid");
    SimplePast simplePast4 = new SimplePast(4, "take", "took", "takenid");
    SimplePast simplePast5 = new SimplePast(5, "come", "came", "comeid");
    SimplePast simplePast6 = new SimplePast(6, "see", "saw", "seenid");
    SimplePast simplePast7 = new SimplePast(7, "know", "knew", "knownid");
    SimplePast simplePast8 = new SimplePast(8, "get", "got", "gotid");
    SimplePast simplePast9 = new SimplePast(9, "give", "gave", "given");
    SimplePast simplePast10 = new SimplePast(10, "find", "found", "found");
    SimplePast simplePast11 = new SimplePast(11, "think", "thought", "thought");
    SimplePast simplePast12 = new SimplePast(12, "tell", "told", "told");
    SimplePast simplePast13 = new SimplePast(13, "become", "became", "become");
    SimplePast simplePast14 = new SimplePast(14, "show", "showed", "shown");
    SimplePast simplePast15 = new SimplePast(15, "leave", "left", "left");
    SimplePast simplePast16 = new SimplePast(16, "feel", "felt", "felt");
    SimplePast simplePast17 = new SimplePast(17, "put", "put", "put");
    SimplePast simplePast18 = new SimplePast(18, "bring", "brought", "brought");
    SimplePast simplePast19 = new SimplePast(19, "begin", "began", "begun");
    SimplePast simplePast20 = new SimplePast(20, "keep", "kept", "kept");
    SimplePast simplePast21 = new SimplePast(21, "hold", "held", "held");
    SimplePast simplePast22 = new SimplePast(22, "write", "wrote", "written");
    SimplePast simplePast23 = new SimplePast(23, "stand", "stood", "stood");
    SimplePast simplePast24 = new SimplePast(24, "hear", "heard", "heard");
    SimplePast simplePast25 = new SimplePast(25, "let", "let", "let");
    SimplePast simplePast26 = new SimplePast(26, "mean", "meant", "meant");
    SimplePast simplePast27 = new SimplePast(27, "set", "set", "set");
    SimplePast simplePast28 = new SimplePast(28, "meet", "met", "met");
    SimplePast simplePast29 = new SimplePast(29, "run", "ran", "run");
    SimplePast simplePast30 = new SimplePast(30, "pay", "paid", "paid");
    SimplePast simplePast31 = new SimplePast(31, "sit", "sat", "sat");
    SimplePast simplePast32 = new SimplePast(32, "speak", "spoke", "spoken");
    SimplePast simplePast33 = new SimplePast(33, "lie", "lay", "lain");
    SimplePast simplePast34 = new SimplePast(34, "lead", "led", "led");
    SimplePast simplePast35 = new SimplePast(35, "read", "read", "read");
    SimplePast simplePast36 = new SimplePast(36, "grow", "grew", "grown");
    SimplePast simplePast37 = new SimplePast(37, "lose", "lost", "lost");
    SimplePast simplePast38 = new SimplePast(38, "fall", "fell", "fallen");
    SimplePast simplePast39 = new SimplePast(39, "send", "sent", "sent");
    SimplePast simplePast40 = new SimplePast(40, "build", "built", "built");
    SimplePast simplePast41 = new SimplePast(41, "understand", "understood", "understood");
    SimplePast simplePast42 = new SimplePast(42, "draw", "drew", "drawn");
    SimplePast simplePast43 = new SimplePast(43, "break", "broke", "broken");
    SimplePast simplePast44 = new SimplePast(44, "spend", "spent", "spent");
    SimplePast simplePast45 = new SimplePast(45, "cut", "cut", "cut");
    SimplePast simplePast46 = new SimplePast(46, "rise", "rose", "risen");
    SimplePast simplePast47 = new SimplePast(47, "drive", "drove", "driven");
    SimplePast simplePast48 = new SimplePast(48, "buy", "bought", "bought");
    SimplePast simplePast49 = new SimplePast(49, "wear", "wore", "worn");
    SimplePast simplePast50 = new SimplePast(50, "choose", "chose", "chosen");
    SimplePast simplePast51 = new SimplePast(51, "seek", "sought", "sought");
    SimplePast simplePast52 = new SimplePast(52, "throw", "threw", "thrown");
    SimplePast simplePast53 = new SimplePast(53, "catch", "caught", "caught");
    SimplePast simplePast54 = new SimplePast(54, "deal", "dealt", "dealt");
    SimplePast simplePast55 = new SimplePast(55, "win", "won", "won");
    SimplePast simplePast56 = new SimplePast(56, "forget", "forgot", "forgotten");
    SimplePast simplePast57 = new SimplePast(57, "lay", "laid", "laid");
    SimplePast simplePast58 = new SimplePast(58, "sell", "sold", "sold");
    SimplePast simplePast59 = new SimplePast(59, "fight", "fought", "fought");
    SimplePast simplePast60 = new SimplePast(60, "bear", "bore", "borne");
    SimplePast simplePast61 = new SimplePast(61, "teach", "taught", "taught");
    SimplePast simplePast62 = new SimplePast(62, "eat", "ate", "eaten");
    SimplePast simplePast63 = new SimplePast(63, "sing", "sang", "sung");
    SimplePast simplePast64 = new SimplePast(64, "strike", "struck", "struck");
    SimplePast simplePast65 = new SimplePast(65, "hang", "hung", "hung");
    SimplePast simplePast66 = new SimplePast(66, "shake", "shook", "shaken");
    SimplePast simplePast67 = new SimplePast(67, "ride", "rode", "ridden");
    SimplePast simplePast68 = new SimplePast(68, "feed", "fed", "fed");
    SimplePast simplePast69 = new SimplePast(69, "shoot", "shot", "shot");
    SimplePast simplePast70 = new SimplePast(70, "drink", "drank", "drunk");
    SimplePast simplePast71 = new SimplePast(71, "hit", "hit", "hit");
    SimplePast simplePast72 = new SimplePast(72, "arise", "arose", "arisen");
    SimplePast simplePast73 = new SimplePast(73, "fly", "flew", "flown");
    SimplePast simplePast74 = new SimplePast(74, "spread", "spread", "spread");
    SimplePast simplePast75 = new SimplePast(75, "sleep", "slept", "slept");
    SimplePast simplePast76 = new SimplePast(76, "cost", "cost", "cost");
    SimplePast simplePast77 = new SimplePast(77, "beat", "beat", "beaten");
    SimplePast simplePast78 = new SimplePast(78, "light", "lit", "lit");
    SimplePast simplePast79 = new SimplePast(79, "bind", "bound", "bound");
    SimplePast simplePast80 = new SimplePast(80, "cast", "cast", "cast");
    SimplePast simplePast81 = new SimplePast(81, "hide", "hid", "hidden");
    SimplePast simplePast82 = new SimplePast(82, "swing", "swung", "swung");
    SimplePast simplePast83 = new SimplePast(83, "blow", "blew", "blown");
    SimplePast simplePast84 = new SimplePast(84, "swim", "swam", "swum");
    SimplePast simplePast85 = new SimplePast(85, "bend", "bent", "bent");
    SimplePast simplePast86 = new SimplePast(86, "wake", "woke", "woken");
    SimplePast simplePast87 = new SimplePast(87, "stick", "stuck", "stuck");
    SimplePast simplePast88 = new SimplePast(88, "sweep", "swept", "swept");
    SimplePast simplePast89 = new SimplePast(89, "undertake", "undertook", "undertaken");
    SimplePast simplePast90 = new SimplePast(90, "shut", "shut", "shut");
    SimplePast simplePast91 = new SimplePast(91, "steal", "stole", "stolen");
    SimplePast simplePast92 = new SimplePast(92, "tear", "tore", "torn");
    SimplePast simplePast93 = new SimplePast(93, "hurt", "hurt", "hurt");
    SimplePast simplePast94 = new SimplePast(94, "ring", "rang", "rung");
    SimplePast simplePast95 = new SimplePast(95, "lend", "lent", "lent");
    SimplePast simplePast96 = new SimplePast(96, "sink", "sank", "sunk");
    SimplePast simplePast97 = new SimplePast(97, "overcome", "overcame", "overcome");
    SimplePast simplePast98 = new SimplePast(98, "freeze", "froze", "frozen");
    SimplePast simplePast99 = new SimplePast(99, "shine", "shone", "shone");
    SimplePast simplePast100 = new SimplePast(100, "withdraw", "withdrew", "withdrawn");

    public SimplesPastFactory() {
        list.add(simplePast1);
        list.add(simplePast2);
        list.add(simplePast3);
        list.add(simplePast4);
        list.add(simplePast5);
        list.add(simplePast6);
        list.add(simplePast7);
        list.add(simplePast8);
        list.add(simplePast9);
        list.add(simplePast10);
        list.add(simplePast11);
        list.add(simplePast12);
        list.add(simplePast13);
        list.add(simplePast14);
        list.add(simplePast15);
        list.add(simplePast16);
        list.add(simplePast17);
        list.add(simplePast18);
        list.add(simplePast19);
        list.add(simplePast20);
        list.add(simplePast21);
        list.add(simplePast22);
        list.add(simplePast23);
        list.add(simplePast24);
        list.add(simplePast25);
        list.add(simplePast26);
        list.add(simplePast27);
        list.add(simplePast28);
        list.add(simplePast29);
        list.add(simplePast30);
        list.add(simplePast31);
        list.add(simplePast32);
        list.add(simplePast33);
        list.add(simplePast34);
        list.add(simplePast35);
        list.add(simplePast36);
        list.add(simplePast37);
        list.add(simplePast38);
        list.add(simplePast39);
        list.add(simplePast40);
        list.add(simplePast41);
        list.add(simplePast42);
        list.add(simplePast43);
        list.add(simplePast44);
        list.add(simplePast45);
        list.add(simplePast46);
        list.add(simplePast47);
        list.add(simplePast48);
        list.add(simplePast49);
        list.add(simplePast50);
        list.add(simplePast51);
        list.add(simplePast52);
        list.add(simplePast53);
        list.add(simplePast54);
        list.add(simplePast55);
        list.add(simplePast56);
        list.add(simplePast57);
        list.add(simplePast58);
        list.add(simplePast59);
        list.add(simplePast60);
        list.add(simplePast61);
        list.add(simplePast62);
        list.add(simplePast63);
        list.add(simplePast64);
        list.add(simplePast65);
        list.add(simplePast66);
        list.add(simplePast67);
        list.add(simplePast68);
        list.add(simplePast69);
        list.add(simplePast70);
        list.add(simplePast71);
        list.add(simplePast72);
        list.add(simplePast73);
        list.add(simplePast74);
        list.add(simplePast75);
        list.add(simplePast76);
        list.add(simplePast77);
        list.add(simplePast78);
        list.add(simplePast79);
        list.add(simplePast80);
        list.add(simplePast81);
        list.add(simplePast82);
        list.add(simplePast83);
        list.add(simplePast84);
        list.add(simplePast85);
        list.add(simplePast86);
        list.add(simplePast87);
        list.add(simplePast88);
        list.add(simplePast89);
        list.add(simplePast90);
        list.add(simplePast91);
        list.add(simplePast92);
        list.add(simplePast93);
        list.add(simplePast94);
        list.add(simplePast95);
        list.add(simplePast96);
        list.add(simplePast97);
        list.add(simplePast98);
        list.add(simplePast99);
        list.add(simplePast100);
    }
}
